---
- hosts: all
  become: true
  name: Add hosts to /etc/hosts
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |-
          192.168.56.21 db-vm-1.jbt.pl db-vm-1
          192.168.56.22 db-vm-2.jbt.pl db-vm-2
          192.168.56.23 db-vm-3.jbt.pl db-vm-3
