---
- hosts: all
  become: true
  name: Add hosts to /etc/hosts
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |-
          192.168.148.118 db-vm-1.jbt.pl
          192.168.148.121 db-vm-2.jbt.pl
          192.168.148.117 db-vm-3.jbt.pl
