---
- hosts: all
  become: true
  name: Install Cassandra Database
  vars:
    interface: eth0 # eth0 for gcp, eth1 for vagrant, eno1 for lab
  tasks:
    - name: Install java-1.8.0
      ansible.builtin.yum:
        name:
          - java-1.8.0-openjdk
        state: present

    - name: Add Cassandra yum repository
      ansible.builtin.yum_repository:
        name: cassandra
        description: Apache Cassandra
        baseurl: https://redhat.cassandra.apache.org/41x/
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: https://downloads.apache.org/cassandra/KEYS

    - name: Install cassandra packages
      ansible.builtin.yum:
        name:
          - cassandra
        state: present

    - name: Pin Cassandra packages to fix db version
      ansible.builtin.lineinfile:
        path: /etc/yum.conf
        line: exclude=cassandra

    - name: Copy cassandra conf file from host
      ansible.builtin.copy:
        src: ../cfgs/cassandra.yaml
        dest: /etc/cassandra/conf/cassandra.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Get host IP addr
      ansible.builtin.shell: set -o pipefail && ip a l {{ interface }} | awk '/inet / { print $2 }' | awk -F '/' '{ print $1 }'
      register: ip
      changed_when: false

    - name: Replace IP addr in cassandra.yaml file
      ansible.builtin.replace:
        path: /etc/cassandra/conf/cassandra.yaml
        regexp: CHANGE_ME
        replace: "{{ ip.stdout }}"

    - name: Permit traffic for storage and native transport ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      loop:
        - 7000/tcp
        - 7199/tcp
        - 9042/tcp

    - name: Start cassandra service
      ansible.builtin.systemd:
        name: cassandra
        state: restarted
        enabled: true
