---
- hosts: all
  become: true
  name: Install Elasticsearch
  tasks:
  - name: Add Elastic yum repository
    ansible.builtin.yum_repository:
      name: elasticsearch
      description: Elasticsearch Repository for 8.x packages
      baseurl: https://artifacts.elastic.co/packages/8.x/yum
      enabled: 1
      gpgcheck: 1
      gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

  - name: Install elasticsearch packages
    ansible.builtin.yum:
      name:
      - elasticsearch
      state: present

  - name: Pin elasticsearch packages to fix db version
    ansible.builtin.lineinfile:
      path: /etc/yum.conf
      line: exclude=elasticsearch