---
- hosts: all
  become: true
  name: Install Cassandra Database
  tasks:
    - name: Install java-1.8.0
      ansible.builtin.yum:
        name:
          - java-1.8.0-openjdk
        state: present

    - name: Add Cassandra yum repository
      ansible.builtin.yum_repository:
        name: cassandra
        description: Apache Cassandra
        baseurl: https://redhat.cassandra.apache.org/41x/
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: https://downloads.apache.org/cassandra/KEYS

    - name: Install cassandra packages
      ansible.builtin.yum:
        name:
          - cassandra
        state: present

    - name: Pin Cassandra packages to fix db version
      ansible.builtin.lineinfile:
        path: /etc/yum.conf
        line: exclude=cassandra

    - name: Get host IP addr
      ansible.builtin.shell: set -o pipefail && ip a l eth1 | awk '/inet / { print $2 }' | awk -F '/' '{ print $1 }'
      register: ip
      changed_when: false

    - name: Change cluster name to jbt-cluster
      ansible.builtin.replace:
        path: /etc/cassandra/conf/cassandra.yaml
        regexp: "cluster_name: 'Test Cluster'"
        replace: "cluster_name: 'jbt-cluster'"

    # In default config changes only listen_address and rpc_address
    - name: Replace localhost with vm IP addr in cassandra.conf
      ansible.builtin.replace:
        path: /etc/cassandra/conf/cassandra.yaml
        regexp: localhost
        replace: "{{ ip.stdout }}"

    # TODO Check if it is correct, it works, but not sure how
    - name: Change seeds to vms IP addr
      ansible.builtin.replace:
        path: /etc/cassandra/conf/cassandra.yaml
        regexp: 'seeds: "127.0.0.1:7000"'
        replace: 'seeds: "{{ ip.stdout }}:7000"'

    - name: Permit traffic for storage and native transport ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      loop:
        - 7000/tcp
        - 7199/tcp
        - 9042/tcp

    - name: Start cassandra service
      ansible.builtin.systemd:
        name: cassandra
        state: restarted
        enabled: true
