---
- hosts: all
  become: true
  name: Set up MongoDB Replicaset
  vars:
    interface: eth0 # eth0 for gcp, eth1 for vagrant, eno1 for lab
  tasks:
    - name: Copy config
      ansible.builtin.copy:
        src: ../cfgs/mongod.conf
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: "0644"

    - name: Get node IP addr
      ansible.builtin.shell: set -o pipefail && ip a l {{ interface }} | awk '/inet / { print $2 }' | awk -F '/' '{ print $1 }'
      register: ip
      changed_when: false

    - name: Replace IP addr in mongod.conf file
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: CHANGE_ME
        replace: "{{ ip.stdout }}"

    - name: Permit traffic in default zone for mongo service
      ansible.posix.firewalld:
        port: 27017/tcp
        state: enabled
        permanent: true
        immediate: true

    - name: Start mongod service
      ansible.builtin.systemd:
        name: mongod
        state: restarted
        enabled: true
