---
- hosts: all
  become: true
  name: Set up MongoDB Replicaset
  tasks:
  # TODO, USE KEYFILES
  # - name: Copy keyfile
  #   ansible.builtin.copy:
  #     src: ../cfgs/mongo-keyfile # change with `openssl rand -base64 756 > mongo-keyfile`
  #     dest: /home/vagrant/.mongo-security/
  #     owner: mongod
  #     group: mongod
  #     mode: '0400'

    - name: Copy config
      ansible.builtin.copy:
        src: ../cfgs/mongod.conf
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: "0644"

    - name: Get node IP addr
      ansible.builtin.shell: set -o pipefail && ip a l eno1 | awk '/inet / { print $2 }' | awk -F '/' '{ print $1 }'
      register: ip
      changed_when: false

    - name: Replace IP addr in mongod.conf file
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: CHANGE_ME
        replace: "{{ ip.stdout }}"

    - name: Permit traffic in default zone for mongo service
      ansible.posix.firewalld:
        port: 27017/tcp
        state: enabled
        permanent: true
        immediate: true

    - name: Start mongod service
      ansible.builtin.systemd:
        name: mongod
        state: restarted
        enabled: true
