name: Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  playbooks_kics_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Mkdir ansible-scan-results
        run: mkdir -p ansible-scan-results
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@latest
        with:
          path: 'db-provisioning'
          output_path: ansible-scan-results
          platform_type: ansible
          output_formats: 'json,sarif'
      - name: Show results
        run: |
          cat results-dir/results.sarif
          cat results-dir/results.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results-dir/results.sarif
