#! vagrant

BOX = "generic/alma8"
N = 1

Vagrant.configure("2") do |config|
  (1..N).each do |i|
    config.vm.define "db-vm-#{i}" do |srv|
        srv.vm.box = BOX
        srv.vm.network "private_network", ip: "192.168.56.#{i + 20}"
        srv.vm.hostname = "db-vm-#{i}"
        srv.ssh.insert_key = true
        srv.ssh.forward_agent = true
        srv.vm.provider "virtualbox" do |vb|
            vb.memory = 4096
            vb.cpus = 2
            vb.name = "db-vm-#{i}"
        end
        srv.vm.provision "ansible" do |ansible|
          ansible.playbook="playbooks/add-hosts.yaml"
        end
    end
  end
end
