#! vagrant

BOX = "generic/alma8"
N=3

Vagrant.configure("2") do |config|
  (1..N).each do |i|
    config.vm.define "database-srv-#{i}" do |srv|
        srv.vm.box = BOX
        srv.vm.network "private_network", ip: "192.168.56.#{i + 20}"
        srv.vm.hostname = "database-srv-#{i}"
        srv.ssh.insert_key = false
        srv.ssh.forward_agent = true
        srv.vm.provider "virtualbox" do |vb|
            vb.memory = 4096
            vb.cpus = 4
            vb.name = "database-srv"
        end
      srv.vm.provision "ansible" do |ansible|
        ansible.playbook="playbooks/mongo-replicaset.yaml"
      end
    end
  end
end
